### ISSUE TITLE
ARMAConv Example

### ISSUE THREAD

**Issue by rusty1s** [danielegrattarola/spektral#1]
Hi,
I would really appreciate it if you could provide a CORA example of the ARMAConv.

**Comment by danielegrattarola** [comment]
Hi Matthias, 

the ARMAConv layer can be used as a drop-in replacement for GraphConv, the API is the same.
Here's an example to use ARMA instead of GCN in `semi_sup_classification_gcn.py`:

```python
# ...
graph_conv_1 = ARMAConv(16,
                        ARMA_K=3,  # number of parallel filters 
                        ARMA_D=2,  # depth of each filter
                        recurrent=True,
                        dropout_rate=0.5,
                        activation='relu',
                        gcn_activation='relu',
                        kernel_regularizer=l2(5e-4),
                        use_bias=True)([X_in, fltr_in])
# ...
```

However, the Laplacian used for GCN is not suitable for ARMA, and I'm currently in the process of cleaning up the relevant code. 
I'll leave the issue open and give you an update once the code is pushed.

Cheers, 
Daniele
