### ISSUE TITLE
Is there any way to assert mode?

### ISSUE THREAD

**Issue by JackMaguire** [danielegrattarola/spektral#108]
My training is giving NAN loss if I run in batch mode with any batch size larger than 1. I'm starting to think I'm just in the wrong mode but I can't find a way to say `assert mode == 'batch'`. Do you have any tips on how to do this?

FWIW my shapes conform to the dimensions listed in the documentation for batch mode. I'm mostly looking for a sanity check API if nothing else.

Thanks as always!

**Comment by danielegrattarola** [comment]
Hey, 

there is an undocumented module in the backed to check your data, although it only works for adjacency matrix and node features (no edge attributes):

```python
import tensorflow as tf
from spektral.layers.ops import modes

b = 32
n = 10
f = 5

# Batch mode
a = tf.ones((b, n, n))
x = tf.ones((b, n, f))

assert modes.autodetect_mode(a, x) == modes.BATCH
```

If this check passes, then layers should work as expected (since they use this internally). Mode compatibility is one of the few things that I test at each commit, so if the data is in the correct shape everything should work. 

If you have NaNs, it may be due to some all-zero row/feature/matrix somewhere, that's usually what happens although I would need to see the actual code to have a better intuition.

Hope this helps 
Cheers

**Comment by JackMaguire** [comment]
That's perfect. Thanks so much!

**Comment by JackMaguire** [comment]
> If you have NaNs, it may be due to some all-zero row/feature/matrix somewhere

**Comment by danielegrattarola** [comment]
That's indeed what you're supposed to do, but you need to be careful once you have zero-padded the graphs if you run any other pre-processing operations. 
It's just something to keep an eye out for... NaNs usually come out from division by zero or exploding losses, so just keep that in mind.
