### ISSUE TITLE
Keras BatchNormalization and Spektral: layer incompatibility

### ISSUE THREAD

**Issue by tdrxy** [danielegrattarola/spektral#129]
Whenever I try to add a BatchNormalizationLayer I get the following error:

> ValueError: Input 0 of layer batch_normalization_1 is incompatible with the layer: expected ndim=2, found ndim=3. Full shape received: [None, None, 12]

Part of the code where it goes wrong:
```
X_in = Input(shape=(F, ))
A_in = Input(shape=(N, ), sparse=True, dtype=dataset[0].a.dtype)

gc_1 = GCNConv(channels=12, activation='relu', use_bias=False)([X_in, A_in])
bn_1 = BatchNormalization()(gc_1)
...
```
Network architecture up until that point:
![image](https://user-images.githubusercontent.com/5569261/101103790-fa5c8c80-35c9-11eb-8165-f17ad9ccdaa4.png)

Could anyone offer me some insight as to what's going wrong?

**Comment by danielegrattarola** [comment]
Hi, 

Your model expects the node features to be 2-dimensional (`[None, 12]`) but you are giving it a Tensor with shape `[None, None, 12]`. 
You have two solutions: 

1. Change the Input layers to reflect the actual shape of your data
2. Change the model definition to use model-sublcassing instead of the traditional API, so that Keras will infer the shape of the data automatically for you.

Cheers
