### ISSUE TITLE
about nx_to_numpy from spektral.utils

### ISSUE THREAD

**Issue by fylinhub** [danielegrattarola/spektral#131]
Hi, 
I've been using the function of nx_to_numpy from the 0.6.2 spektral version. 
But it seems that the conversion.py is no longer available in the utils of the latest version, thus nx_to_numpy was not available as well. 

Is there an equivalent to nx_to_numpy? Thank you!

**Comment by danielegrattarola** [comment]
Yes, I removed that function because it was not used anywhere in the library and was not really meant to be part of the library's API (not tested, slow, etc).
I'm sorry if your code relied on it. You can still access the function [here](https://github.com/danielegrattarola/spektral/blob/a2cd265a9440831afc441c1774dd1b7d080a59f8/spektral/utils/conversion.py), I would suggest you to copy-paste the function in your project if you still need it. 

Cheers, 
Daniele

**Comment by fylinhub** [comment]
Thank you for this information!
