### ISSUE TITLE
citation_gcn l2 regularization

### ISSUE THREAD

**Issue by jackd** [danielegrattarola/spektral#145]
Prior versions used `l2_reg=5e-4 / 2` which is consistent with the original paper (which used `5e-4` in `tf.nn.l2_loss`, which has a division by 2 that `tf.keras.regularizers.l2` does not have). This has recently been changed to `l2_reg=5e-4`. Was this change intentional?

**Comment by danielegrattarola** [comment]
It was intentional since I did not remember why it was there in the first place and I thought that it was leftover from experimenting with hyperparameters :D

This issue reminded me of why I put that `/ 2 ` in the first place, nice catch. 

I will be restoring the old config and also update citation_gcn_custom.py.

Thanks
