### ISSUE TITLE
"TypeError: 'NoneType' object is not callable" when implementing GraphSageConv

### ISSUE THREAD

**Issue by AlfredChenZH** [danielegrattarola/spektral#185]
Hi, Daniel. This python library you developed is of much help for me. However, when I implement the GraphSageConv class as a layer stacked in a line of layers to train, a "TypeError: 'NoneType' object is not callable" pops out and I am not sure how I should fix it. The model I implement is designed as follows:
```python
input_1 = Input(shape=(len_date, d_feat))
adjmat_input = Input(shape=(None,), sparse=True)

hidden1 = BatchNormalization(name='LSTM_BN1')(LSTM(30, input_shape=(input_1.shape[1], input_1.shape[2]))(input_1))
graphsage = GraphSageConv(channels=hidden1.shape[-1], 
                          aggregate="mean", 
                          activation="linear")([hidden1, adjmat_input])
hidden = Dense(1, kernel_initializer='truncated_normal', activation='linear')(graphsage)
model = Model(inputs=[input_1, adjmat_input], outputs=hidden)
opt = optimizers.Adam(lr=0.00002)
model.compile(loss="mse", optimizer=opt, metrics=[pearson_r])
```

when I use model.train_on_batch & model.fit to train the model, my input for input1 is a 489 * 30 * 15 feature matrix and adjmat_input a tf.SparseTensor as how your AdjToSpTensor method runs. And it turns out to hace the following error messages:
```python
Traceback (most recent call last):

  File "<ipython-input-207-42795d53dd9e>", line 1, in <module>
    model.fit([x_train, adj_zz500], y_train)

  File "C:\Users\alfre\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)

  File "C:\Users\alfre\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)

  File "C:\Users\alfre\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable

TypeError: 'NoneType' object is not callable
```
Could you help me out on how to fix this problem?
Thank you very much!

Alfred Chen
Feb 26, 2021

**Comment by danielegrattarola** [comment]
Hi, 

unfortunately you cannot use `model.fit` like that, because Keras assumes that all your graphs have the same shape `[batch, ...]`. Instead, your data is in [mixed mode](https://graphneural.network/data-modes/#mixed-mode) and so you have to use a MixedLoader to load your batches.

Two possibilities: 

1. after creating a MixedLoader, you can call `model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch)`
2. copy the custom training loop from [here](https://github.com/danielegrattarola/spektral/blob/master/examples/other/graph_signal_classification_mnist.py). This will give you more control over the data.

You can also skip the MixedLoader and create your batches manually, but you have to use the training functions at point 2. above. Since TF 2.4 the `model.train_on_batch` function has additional constraints that make it impossible to use with graphs. 

Cheers

**Comment by AlfredChenZH** [comment]
Thank you Daniel! It works perfectly!
