### ISSUE TITLE
`TUDataset` URL for readme is out of date

### ISSUE THREAD

**Issue by nathanbegbie** [danielegrattarola/spektral#195]
In the class documentation for `TUDataset` which appears [here](https://github.com/danielegrattarola/spektral/blob/master/spektral/datasets/tudataset.py#L38-L39) and thus [here in the docs](https://graphneural.network/datasets/#tudataset) it doesn't make sense as to where to find the ReadMe.

After a bit of digging I found a downloadable zip at https://chrsmrrs.github.io/datasets/docs/datasets/ but I'm not sure if that's the readme that the documentation is referring to.

Thanks for maintaining this package!

**Comment by danielegrattarola** [comment]
Hi, 

if you navigate to the folder `~/.spektral/datasets/TUDataset/` you will see folders containing all the datasets that you have downloaded locally, each of which will contain a README.md file describing the dataset.

For instance, after downloading the `PROTEINS` dataset you will can see its details in `~/.spektral/datasets/TUDataset/PROTEINS/README.md`.

I will update the docs to make this more clear, also because right now there is a typo in the path. 

Cheers

**Comment by nathanbegbie** [comment]
Ah, thanks so much! Sorry, I also realise that I misinterpreted that it meant that it existed locally on my machine and not in the docs or online.

Thanks for the quick response 😄

**Comment by danielegrattarola** [comment]
I've updated the docs, indeed they needed to be improved. 

Thanks!
