### ISSUE TITLE
adjacency matrix normalization

### ISSUE THREAD

**Issue by XMAHA** [danielegrattarola/spektral#21]
Hi, Thanks for your great works, I am a beginner of the GNN, they are really useful for me.

In Kipf and Welling GCN, the adjacency matrix needs to add a self-loop, and be renormalized then. In your work, the localpooling_filter function is designed to this operation. And it is used in "node_classification_gcn.py" demo, but not in the "regression_molecules_graph_batch.py". But they both use the GraphConv function. So, why the "regression_molecules_graph_batch.py" doesn't perform the localpooling_filter? And some other demos only use normalized_adjacency function, without adding self-loop "In".

And I am trying use GCN to classify some vibration signal. The performance is really good when the localpooling_filter function do not involved  in the code just like the "regression_molecules_graph_batch.py" demo, but it becomes untrainable when I use tlideA =localpooling_filter(A) to feed the network. 

Looking forward for your reply~:）

**Comment by danielegrattarola** [comment]
Hi, 

that's actually a very interesting question imo. 

If you don't have any type of self-loop in A, then for each node GCN is only able to see its 1-hop neighborhood, but not the node itself. To fix this, Kipf & Welling's solution was to consider each node as part of its own neighbourhood (i.e., the self-loops) and then re-normalize A.

However, this particular issue is not present in all nodes. For instance, GraphSage, ARMA, GIN, and GCS are able to "see" the features of a node, and not only its neighbors. Usually, this is because the node feature are considered separately from the neighbors' features, e.g., via a skip connection or by concatenation.

The reason why in `regression_molecules_graph_batch.py` we use `normalize_adjacency` and not `localpooling_filter` is because the network is composed of `GraphConvSkip` layers, that have an internal skip connection to account for the original node features after propagating the neighbors'. 

Other examples should follow the same concepts. 
If you're doing graph classification with `GraphConvSkip`, then this could be the reason why you see worse performance when using `localpooling_filter`: you don't need to add a self-loop, you're already taking X into account. 

Hope this helps. 
Cheers, 
Daniele
