### ISSUE TITLE
Modifying Adjacency Matrix in gat_conv.py

### ISSUE THREAD

**Issue by sidhomj** [danielegrattarola/spektral#220]
I'm not sure what the purpose of lines 226,227 in gat_conv.py but they seem to modifying the provided adjacency matrix which I imagine is not something a user might want. Should these lines be removed?

```
    def _call_dense(self, x, a):
        shape = tf.shape(a)[:-1]
        **a = tf.linalg.set_diag(a, tf.zeros(shape, a.dtype))
        a = tf.linalg.set_diag(a, tf.ones(shape, a.dtype))**
        x = tf.einsum("...NI , IHO -> ...NHO", x, self.kernel)
        attn_for_self = tf.einsum("...NHI , IHO -> ...NHO", x, self.attn_kernel_self)
        attn_for_neighs = tf.einsum(

```

**Comment by danielegrattarola** [comment]
Hi, 

what version of Spektral is this? 

Current version was fixed a while ago: 
https://github.com/danielegrattarola/spektral/blob/e99d5955a80eeae3c4605d8479f53aaa0ef5dbf2/spektral/layers/convolutional/gat_conv.py#L226

Anyway, the reason for adding self loops is that otherwise the layer would only read messages from the neighbors and not the ego node. This is consistent with the original GAT implementation. 

Cheers

**Comment by sidhomj** [comment]
this is in spektral==1.0.6 when installed via pypi... i'm not sure if the pypi version is the most recent one?

As for the implementation, I feel like one might want a more general form of this convolution where the user can specify doing only convolutions are neighbors (i.e. in the case of learning pure interactions). the current implementation does not allow someone to override this behavior in the case they do not want their adjacency matrix to have ones down the diagonal.

**Comment by danielegrattarola** [comment]
Yeah I haven't updated the package in a while, I'll make sure to push 1.0.7 soon. 

Also, I agree with your perspective. I'll add a flag to make this behaviour optional.
Stay tuned

**Comment by sidhomj** [comment]
thank you!! much appreciated!!
