### ISSUE TITLE
GraphVAE

### ISSUE THREAD

**Issue by AI-Guru** [danielegrattarola/spektral#24]
Hi!

I am very curious! Do you haven an opinion about GraphVAE?
https://hal.archives-ouvertes.fr/hal-01990381/file/icann_paper_long.pdf

Best,
Tristan

**Comment by danielegrattarola** [comment]
I think it's a very nice work with some useful applications, it was actually one of the first GNN papers I implemented. You can build one using `spektral.layers.GraphConv` and `spektral.layers.InnerProduct`, if you are interested. 

I'm going to close the issue because it's more of a personal discussion, but shoot me an email if you want to chat. 

Best, 
Daniele
