### ISSUE TITLE
In the new release index_i index_j flipped in the message_passing layer code

### ISSUE THREAD

**Issue by abmukho** [danielegrattarola/spektral#240]
While comparing my old trained model using crystal conv after implementing the new changes from the new release, I noticed that the index_i and index_j are flipped in the new version in the message_passing code. For example in the previous release, index_i was a.indices[:, 0] which intuitively made more sense because with get_i (self) and get_j(neighbours), the message passing was performed using convolution done on x_i||x_j||e_ij which you then pool on unique x_i's using deserialize scatter. Is there anything subtle in the new release that I am missing? Few explanations that I came up with are that either e_ij is now actually e_ji or a_ij is now a_ji... which I didn't see in the code. What am I missing? This will be a problem in e.g. bidirectional asymmetric edge matrix.

**Comment by danielegrattarola** [comment]
Hi, 

the message passing should be from source (neighbors) to targets, so get_j() should actually return the a.indices[:, 0] because that's the "source" side of the edges.
The order with which we gather edges did not change with this modification, i.e. the first row of x_i, x_j and e are always associated with the first edge. It's just the flow of information that's reversed. 

But yeah, in your example it should be x_i | x_j | e_ji. 
I'll fix the docs 

Cheers
