### ISSUE TITLE
[Feature request] Batch mode for GINconv

### ISSUE THREAD

**Issue by edshui** [danielegrattarola/spektral#280]
Dear All:

I was wondering if it would be possible to make GINconv run on batch mode?

Many thanks!
Ed

**Comment by danielegrattarola** [comment]
Hi, 

you can implement a custom layer that extends `spektral.layers.Conv` instead of  `spektral.layers.MessagePassing`.

The `__init__` and `build` methods should be identical to the ones of `GINConv`, and the call method should be changed to:

```python
from spektral.layers import ops

def call(self, inputs, **kwargs):
    x, a = inputs
    output = self.mlp((self.one + self.eps) * x + ops.modal_dot(a, x))

    return output
```

I'll mark this issue as a feature request so that eventually I'll get around to implementing it :)

Cheers

**Comment by edshui** [comment]
Hi Daniel:

That's neat indeed! Currently the way I got around it is to run GINConv in disjoint mode with the use of DisjointLoader as input to tensorflow.keras.model.fit. It did take me a while to make things right though with my non-CS background;) 

Many thanks for your help! 

Ed


> Hi,
> 
> you can implement a custom layer that extends `spektral.layers.Conv` instead of `spektral.layers.MessagePassing`.
> 
> The `__init__` and `build` methods should be identical to the ones of `GINConv`, and the call method should be changed to:
> 
> ```python
> from spektral.layers import ops
> 
> def call(self, inputs, **kwargs):
>     x, a = inputs
>     output = self.mlp((self.one + self.eps) * x + ops.modal_dot(a, x))
> 
>     return output
> ```
> 
> I'll mark this issue as a feature request so that eventually I'll get around to implementing it :)
> 
> Cheers
