### ISSUE TITLE
Disjoint MNIST Dataset?

### ISSUE THREAD

**Issue by kmader** [danielegrattarola/spektral#31]
So my intuitive guess for how the MNIST dataset worked would be classifying the graph of just the positive pixels into 0-9. The example being a 2.
![image](https://user-images.githubusercontent.com/116120/70146896-7795ae80-16a3-11ea-944d-ec0d8d064330.png)

 Is that an interesting problem to use as a benchmark for classification or is the fixed adjacency matrix and varying features better suited?

**Comment by danielegrattarola** [comment]
I've never seen what you suggest in the literature. 
The 8-NN graph setting is taken from [Defferrad et al. (2016)](https://arxiv.org/abs/1606.09375), and it's interesting because it's a problem of graph signal classification: same topology, different features. 

A GNN should not be able to distinguish the graph in the picture from a 5. If you remove the black pixels it should become almost impossible to classify MNIST, unless you encode spatial positions explicitly.

**Comment by kmader** [comment]
Thanks for the link, and the 2 and 5 point while intuitive, those digits don't get confused very often (they aren't however very accurately predicted)
![image](https://user-images.githubusercontent.com/116120/70221008-cb59d380-1747-11ea-851f-6b6298196cd0.png)

It seems to learn to recognize tips and twists very well, but struggle to count them which  might be a weakness of the global attention layer. 
![image](https://user-images.githubusercontent.com/116120/70221296-5fc43600-1748-11ea-973e-a2ac7d9d6d7c.png)


- Without spatial information (34%)
https://www.kaggle.com/kmader/disjoint-mnist-graph-deep-learning/
-With spatial coordinates as features of vectors (87%)
https://www.kaggle.com/kmader/disjoint-mnist-graph-with-xy

- Dataset
https://www.kaggle.com/kmader/mnist-based-graphs

**Comment by danielegrattarola** [comment]
Yeah, that 34% accuracy without coordinates does not surprise me. From a topology perspective, the GNN should be able to distinguish three classes depending on how many "holes" are in the graph: {1, 2, 3, 5, 7}, {4, 6, 9, 0}, {8}. I am not too sure about this claim though, I would need to think about it. 

With spatial coordinates instead, it becomes a point cloud so it makes more sense. 87% seems a bit low, considering that on the original grid setting even very simple GNNs get to 99% easily, but it may be due to a number of factors.

Nice work! I am not sure that I would include it as a benchmark dataset in Spektral in order to avoid confusion, but you're doing a nice job for sure.
