### ISSUE TITLE
Pooling layers with fixed topology

### ISSUE THREAD

**Issue by mrkbach** [danielegrattarola/spektral#37]
Hi Daniele,
is there a simple way to use pooling layers, other than the global ones, in case of a fixed graph topology (e.g. fixed node positions in a 3D space) and a set of graph signals? Furthermore i was wondering if it is possible to include the mixed mode in EdgeConditionedConv layers?
Thanks in advance.
Cheers

**Comment by danielegrattarola** [comment]
Unfortunately no pooling layer supports mixed mode, for now. 
Your best bet is to use something like Graclus to pre-coarsen the adjacency matrix, have a look [here](https://github.com/mdeff/cnn_graph) for implementation. 

I am currently working to implement a couple of algorithms that may work for your case, but I have no idea when I'll be able to release them. 

As for mixed mode ECC, this is also coming down the line. I have an idea to significantly re-write to backend to improve both performance and support for the different modes. For now, your best workaround is to replicate the adjacency matrix, although I realize this is extremely expensive because ECC wants dense inputs. 

I'll update this issue when I have news.

**Comment by danielegrattarola** [comment]
Closing this since ECC now supports mixed mode.
