### ISSUE TITLE
Running example on "Getting started"

### ISSUE THREAD

**Issue by FaranakAk** [danielegrattarola/spektral#40]
Hi!
I'm trying to run the example on the "Getting started" page of Spektral website. I'm using the exact codes there. I'm receiving "ValueError:A SciPy sparse matrix was passed to a model that expects dense inputs. Please densify your inputs first, such as by calling `x.toarray()." When I densify X by X = X.todense(): "ValueError: The two structures don't have the same nested structure." And when I change the input by "X_in = Input(shape=(F, ), sparse=True)  # Input layer for X" I receive this error:"TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'". Can you please help me to run this example?

**Comment by danielegrattarola** [comment]
Hi, 

you are right, there are a couple of issues with the code because the example was written for an older version of Spektral. 
I'll update the example soon, however, here's how to fix it in the meantime:
- change imports from `keras` to `tensorlfow.keras`
- convert `X` to dense: `X = X.toarray()`
- convert `A` to float32: `A = A.astype('f4')`

I was able to get the model to train with these changes. Thanks for spotting the issue.

**Comment by danielegrattarola** [comment]
I have fixed the example and it should be live soon, let me know if you still have issues. 
Cheers, 
Daniele
