### ISSUE TITLE
Mincut result

### ISSUE THREAD

**Issue by WhirlFirst** [danielegrattarola/spektral#43]
It seems that Mincut result is  not reproducible. I don't know how to set the seed.

**Comment by danielegrattarola** [comment]
Hi, can you expand a bit more?
What are you trying to reproduce?

**Comment by WhirlFirst** [comment]
Oh yes. I'm just trying to run the example code you gave about mincut repeatedly. But I get different results after each run.
just like:
`100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [00:34<00:00, 145.65it/s]
Homogeneity: 0.410; Completeness: 0.386; NMI: 0.398`

`100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [00:34<00:00, 144.65it/s]
Homogeneity: 0.389; Completeness: 0.366; NMI: 0.378`

**Comment by danielegrattarola** [comment]
Oh, I see.
Yeah, unfortunately it is not straightforward to set a seed in Tensorflow, and in TF1 was it basically impossible to exactly reproduce results. I am not sure whether things changed in TF2, but I don't think so, because most of the non-determinism is due to the underlying CUDA and cuDNN libraries. 
[This StackOverflow thread](https://stackoverflow.com/questions/36288235/how-to-get-stable-results-with-tensorflow-setting-random-seed) has some answers, but in general I would not expect results to always be the same. 

Good luck.

**Comment by WhirlFirst** [comment]
Thank you for you link!
The command  `tf.random.set_seed(1)` works. 
 I think it is necessary to be able to produce a stable output, both for publishing papers and for industrial use. So I think it might be possible to add this command to this example code?
