### ISSUE TITLE
MNIST gcn classification example with pooling layers

### ISSUE THREAD

**Issue by renatojmsdh** [danielegrattarola/spektral#47]
Hi,

I'm trying to use some of the available pooling layers with a GCN in mixed mode. But there are some errors after the definition of the model, in the shape of the computed gradient. I can reproduce the same error with the example *graph_signal_classification_mnist.py* as by adding a DiffPool layer :
```
graph_conv = GraphConv(32,
                       activation='elu',
                       kernel_regularizer=l2(l2_reg),
                       use_bias=True)([X_in, A_in])
graph_conv,A_in2,_ = DiffPool(k=128)([graph_conv,A_in])
graph_conv = GraphConv(32,
                       activation='elu',
                       kernel_regularizer=l2(l2_reg),
                       use_bias=True)([graph_conv, A_in2])
flatten = Flatten()(graph_conv)
```

And the following error occurs:
 ```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 655, in set_shape
    unknown_shape)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 2 and 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_util.py", line 697, in _GradientsHelper
    in_grad.set_shape(t_in.get_shape())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 658, in set_shape
    raise ValueError(str(e))
ValueError: Shapes must be equal rank, but are 2 and 1

During handling of the above exception, another exception occurred:

ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: diff_pool/SparseTensorDenseAdd.  Input index: 1. Original input shape: (7180,).  Calculated input gradient shape: (7180, 784)
 ```
Can you help me with this?

BTW I also was wondering: Is there any example of code using MNIST in single mode, and then compatible with the other pooling layers as TopKPool?

Best

**Comment by danielegrattarola** [comment]
Hi, 

I have just pushed a fix to the `develop` branch that allows your example to run without issues. 
However, it should be noted that the performance of DiffPool in graph signal classification is barely above random. This is likely a structural issue with DiffPool and MNIST, because the node features are not suitable to provide information for pooling. 

TopKPool and the other pooling layers do not support mixed mode. You can try to write a custom training loop where you use the GNN in single mode and accumulate the gradient for each batch (or you can use batch size of 1).

Hope this helps

**Comment by renatojmsdh** [comment]
Thanks @danielegrattarola
