### ISSUE TITLE
Slight Deviation In Code From The ChebyNets Paper?

### ISSUE THREAD

**Issue by ShikharJ** [danielegrattarola/spektral#54]
Hi @danielegrattarola, and thanks for this wonderful piece of work. It is really helpful to people like me who are taking their first steps towards a career in research. I have a minor doubt regarding the implementation of the `ChebConv` layer. According to equation 5 in the [paper](https://arxiv.org/pdf/1606.09375.pdf):

<img src="https://render.githubusercontent.com/render/math?math=y_{s,%20j}=\Sigma_{i}^{F_{in}}g_{\theta_{i,%20j}}(L)x_{s,%20i}%20\in%20R^{n}">

Where `x` is the n-dimensional feature vector, where `n` specifies the number of vertices in the graph. So even if we assume `i` and `j` to be just `1` (a simple case of single input feature vector and single feature output vector), our output should be an n-dimensional vector as well, as stated above.

Now coming to the code, we have:
```
self.kernel = self.add_weight(shape=(self.K, input_dim, self.channels), ...
```
and
```
T_0 = features
output = ops.dot(T_0, self.kernel[0])
```
Here, I'm assuming `features` is an n-dimensional input feature map, just like the  `x` above. So wouldn't the output in this case be a vector with the dimensionality of the number of channels? Am I missing something here?

**Comment by danielegrattarola** [comment]
Hi,

You are right in your analysis of Eq. 5, but you are missing a detail.

Notice how in the paper they are giving you the equation for the i-th node and j-th feature.
Instead, in the code we are doing everything at once, so that when we do:

output = ops.dot(T_0, kernel[0])

the shapes of the matrices are N x F_in and F_in x F_out, resulting in an output of N x F_out.
In the equation, F_out is implicitly 1. What remains is a summation of products, i.e., a matrix multiplication between each j-th node feature and the j-th weight of shape F_in.

Cheers

**Comment by ShikharJ** [comment]
Ah, I see it. Thanks for the help.
