### ISSUE TITLE
Graph with data on only part of the nodes

### ISSUE THREAD

**Issue by solyron** [danielegrattarola/spektral#61]
Hi, 
1) I have a graph where I have data on only part of the nodes(always on single a node, meaning, there are no 2 neighboring nodes with known data).
However, I must keep the adjacency of the full graph, since otherwise the hierarchy between the nodes won't be specified.
Does Spektral provides any suitable platform for this kind of problem?
2) When identifing for example F=2 (dimension of the node attributes=2), the first 2 columns of the training data would be linked to the first node in the graph, and so on?
3) Say that the answer to Q.1 is positive, how are the columns of the data will be attributed to the right nodes in the graph?

Thank you!

**Comment by danielegrattarola** [comment]
Hi, 

to answer your questions: 

1. If I understand correctly, your best course of action is to use "dummy" node attributes for the nodes that don't have attributes. You can set them all to zero, for example. There is no current way to deal with nodes without attributes in Spektral, because you need some form of an attribute in order to do message passing/convolution.

2. If F=2, it means that each node has 2 features. The first **row** of the node features will be associated to the first node, and so on. The overall shape of the node feature matrix is N x F (N nodes, F features). 

3. That's exactly the problem, you would need an extra data structure to assign features to nodes, and it's really more convenient to add dummy attributes. 

Hope that answers your doubts.
Cheers, 
Daniele

**Comment by solyron** [comment]
Thank  you, 

1. About the idea of putting a zero value dummy fature for nodes with no data- 
I would like that for those nodes, there will be no message passing/convolution. I try to think how does putting a zero feature guarantees there would be no passing- 
Perhaps by also asssigning zero to the features of the predictions (in the training) of the nodes with this zero dummy feature? 
Another idea is that for these nodes, I can put zero in all of the features, with no dummy - unless - there is a way to prevent passing/convolution by specifically dedicated feature for this purpose?
2. About my third question- for simplicity, say I have a graph with only 3 nodes- one father with two sons. so matrix A would be 3 by 3. How it is determined if the row/column represented in A is the right son or left son?
meaning, although I can have a feature in matrix X which is the number of the node, in A the number of the row/column is not nessecerily the number of the node.

Best regards

**Comment by danielegrattarola** [comment]
1. Depending on the particular use case, you can do different things: 
- if you want to completely ignore the empty nodes, then it's better to remove them entirely or disconnect them from the rest of the graph. 
- if you want to keep the nodes because you want to propagate information through them, then you need to have some form of dummy feature (so that the neighbours can read the information and update it during propagation). Always resetting the features to 0 is equivalent to not doing message passing at all. 
2. You can look at the documentation for [data modes](https://graphneural.network/data/) to see which is your particular case. Usually, the plain `model.fit()` works in "single" and "batch" mode. 
There are template examples for all use cases that you can look at [here](https://graphneural.network/examples/).

Cheers
