### ISSUE TITLE
Applying Keras TimeDistributed Layer

### ISSUE THREAD

**Issue by jasoank** [danielegrattarola/spektral#68]
Hi, I'am relatively new in Keras. My data is temporal graph data (with 100 timeframes) and I'm trying to combine Edge Conditional Convolution [using this example](https://github.com/danielegrattarola/spektral/blob/master/examples/graph_prediction/qm9_batch.py) with LSTM. However I got the error when applying `TimeDistributed` on the Convolution and Pooling layer

> Dimension value must be integer or None or have an __index__ method, got TensorShape ...

My question is, is it possible or how to use Keras `TimeDistributed` alongside Spektral Convolution layer?

Thank you

**Comment by danielegrattarola** [comment]
The error that you posted seems to be more of a Keras issue than a Spektral one. 
Are you sure you are using tf.keras? 

Anyway, I have worked with TimeDistributed in the past and the biggest issue is that Spektral's layers take multiple inputs but TimeDistributed does not support that. If you can find a workaround (like concatenating the inputs in a single tensor and then splitting them back "inside" the TimeDistributed layer) then there should be no problems because Spektral is fully compatible with Keras.

Cheers

**Comment by jasoank** [comment]
Thank you very much for your answer and suggestion!

In my case, I'm concatenating the input and then split them inside the `TimeDistributed` layer. The number of vertex features is 2.

```X_in = Input(shape=(N, F))
A_in = Input((N, N))
concat = concatenate([X_in, A_in])
gc1_layer = GraphAttention(32, activation='relu', kernel_regularizer=l2(l2_reg))
gc1 = TimeDistributed(Lambda(lambda x: gc1_layer([x[:,:,:2], x[:,:,2:]])))(concat)
```

But I got this error:

> ValueError: Index out of range using input dim 2; input has only 2 dims for '{{node time_distributed_19/lambda_16/strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=7, ellipsis_mask=0, end_mask=3, new_axis_mask=0, shrink_axis_mask=0](time_distributed_19/Reshape, time_distributed_19/lambda_16/strided_slice/stack, time_distributed_19/lambda_16/strided_slice/stack_1, time_distributed_19/lambda_16/strided_slice/stack_2)' with input shapes: [?,543], [3], [3], [3] and with computed input tensors: input[3] = <1 1 1>.

**Comment by danielegrattarola** [comment]
Unfortunately I have never seen this before, have you tried following the suggestion and defining a custom Layer to do that operation?
