### ISSUE TITLE
Node classification for whole graph 

### ISSUE THREAD

**Issue by acc4012** [danielegrattarola/spektral#96]
Hi @danielegrattarola,

(Sorry this is not an issue)

Is it possible to have an example or, could you give a guidance for the following problem?

Given N graphs, each graph has a variable number of nodes.
Each node has an associated class.  

How to use Spektral to train a model that learn from those graphs to predict the class of each node of a new graph, where no class is given to any node?

An example problem is this dataset, in which a graph of left-right-top-bottom edge between words can be constructed.  
https://guillaumejaume.github.io/FUNSD/

Thank you.

**Comment by danielegrattarola** [comment]
Hi, 

this is an inductive node classification problem. 
Since you have many graphs of different sizes, you can represent your data in [disjoint mode](https://graphneural.network/data/#disjoint-mode).

Have a look at the examples [here](https://graphneural.network/examples/): you need the general template from "Graph-level prediction, disjoint mode", but 

1. you have to modify the GNN to **not** have a global pooling layer at the end;
2. you have to manually create the targets for each batch by stacking your node labels along the "node" dimension.

Hope this helps. 
Cheers
